class Vms1511Regs:
    SYS_UPTIME = "SYS_UPTIME"
    SYS_REGMAP_VERSION = "SYS_REGMAP_VERSION"
    SYS_STATUS = "SYS_STATUS"
    SYS_COMMAND = "SYS_COMMAND"
    SYS_TEST = "SYS_TEST"
    SYS_IO_INPUT = "SYS_IO_INPUT"
    FACT_SERIAL_NUMBER = "FACT_SERIAL_NUMBER"
    FACT_DEVICE_ID = "FACT_DEVICE_ID"
    FACT_HW_REVISION = "FACT_HW_REVISION"
    FACT_BOOT_REVISION = "FACT_BOOT_REVISION"
    FIRM_REVISION = "FIRM_REVISION"
    FIRM_ASSEMBLY_INFO = "FIRM_ASSEMBLY_INFO"
    FIRM_APP_CHECKSUM = "FIRM_APP_CHECKSUM"
    FIRM_APP_SIZE = "FIRM_APP_SIZE"
    COM_MB_BAUD_RATE = "COM_MB_BAUD_RATE"
    COM_MB_PARITY = "COM_MB_PARITY"
    COM_MB_STOP_BITS = "COM_MB_STOP_BITS"
    COM_RESERVED = "COM_RESERVED"
    COM_MB_ADDRESS = "COM_MB_ADDRESS"
    COM_MB_APPLY = "COM_MB_APPLY"
    COM_MB_TIMEOUT = "COM_MB_TIMEOUT"
    CALIB_MODE = "CALIB_MODE"
    CALIB_RESERVED = "CALIB_RESERVED"
    AMP_GAIN = "AMP_GAIN"
    AMP_LOAD = "AMP_LOAD"
    DBG_WRITES_CONF = "DBG_WRITES_CONF"


class COM_MB_BAUD_RATE:
    MB_BAUD_9600 = 0
    MB_BAUD_19200 = 1
    MB_BAUD_38400 = 2
    MB_BAUD_57600 = 3
    MB_BAUD_115200 = 4


class COM_MB_PARITY:
    MB_PARITY_NONE = 0
    MB_PARITY_EVEN = 1
    MB_PARITY_ODD = 2


class COM_MB_STOP_BITS:
    MB_STOP_1 = 0
    MB_STOP_2 = 1


class AMP_GAIN:
    GAIN_1 = 0
    GAIN_3 = 1
    GAIN_10 = 2
    GAIN_20 = 3


class AMP_LOAD:
    LOAD_100R = 0
    LOAD_1k = 1
    LOAD_2k = 2
    LOAD_10k = 3


